//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PracticalExamples.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Accounts_v
    {
        public int Id { get; set; }
        public int ClientId { get; set; }
        public string AccNo { get; set; }
        public string Status { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string PeronalCode { get; set; }
    }
}
